import { parseAbi } from "viem";

// PanoramaSeason2Auction — multi-unit English auction with uniform clearing price.
// Note (abitype): uintN with N <= 48 decodes to `number`, N > 48 to `bigint`.
// So phase/extensionCount/minIncrementBps/heap ids -> number; amounts/times/prices -> bigint.
//
// One unified ABI: functions + events + errors. Errors MUST be present so viem can decode
// custom reverts (BidTooLow, AuctionEnded, ...) during simulation and receipt replay instead
// of surfacing raw selector hex to the user. Events power the settlement standings and
// per-block refresh.

export const panoramaAuctionAbi = parseAbi([
	// lifecycle / config
	"function phase() view returns (uint8)",
	"function paused() view returns (bool)",
	"function startTime() view returns (uint64)",
	"function endTime() view returns (uint64)",
	"function absoluteEndTime() view returns (uint64)",
	"function reservePrice() view returns (uint96)",
	"function minIncrementBps() view returns (uint16)",
	"function extensionCount() view returns (uint32)",
	"function clearingPrice() view returns (uint96)",
	"function proceeds() view returns (uint256)",
	"function finalizeCursor() view returns (uint256)",
	"function refundCursor() view returns (uint256)",
	"function winnerCount() view returns (uint256)",
	"function remainingBidCount() view returns (uint256)",
	"function refundsComplete() view returns (bool)",
	"function totalEscrowed() view returns (uint256)",
	"function totalPendingReturns() view returns (uint256)",
	"function unreleasedProceeds() view returns (uint256)",
	"function payoutA() view returns (address)",
	"function payoutB() view returns (address)",
	"function nft() view returns (address)",
	"function owner() view returns (address)",
	// constants
	"function MAX_UNITS() view returns (uint256)",
	"function MAX_BIDS_PER_WALLET() view returns (uint8)",
	"function SPLIT_A_BPS() view returns (uint256)",
	"function FINALIZE_GRACE() view returns (uint256)",
	"function EMERGENCY_GRACE() view returns (uint256)",
	"function MAX_TOTAL_EXTENSION() view returns (uint256)",
	"function FIRST_TOKEN_ID() view returns (uint256)",
	"function LAST_TOKEN_ID() view returns (uint256)",
	// derived views
	"function activeBids() view returns (uint256)",
	"function isFull() view returns (bool)",
	"function currentClearingPrice() view returns (uint256)",
	"function lowestActiveBid() view returns (uint256)",
	"function minimumBid() view returns (uint256)",
	"function minIncreaseForExtension() view returns (uint256)",
	"function timeRemaining() view returns (uint256)",
	"function totalLiabilities() view returns (uint256)",
	"function surplusETH() view returns (uint256)",
	"function expectedNftSupply() view returns (uint256)",
	"function supplyMismatched() view returns (bool)",
	"function requiredMintCapForSettlement() view returns (uint256)",
	"function mintingUnavailable() view returns (bool)",
	// per-account
	"function activeBidCount(address who) view returns (uint8)",
	"function pendingReturns(address who) view returns (uint256)",
	"function bidsOf(address who) view returns (uint32[] ids, uint96[] amounts)",
	"function bids(uint32 bidId) view returns (address bidder, uint96 amount)",
	"function heapPos(uint32 bidId) view returns (uint32)",
	"function getBids() view returns (uint32[] ids, address[] bidders, uint96[] amounts)",
	// writes
	"function placeBid() payable",
	"function increaseBid(uint32 bidId) payable",
	"function withdraw()",
	"function finalize(uint256 maxCount)",
	"function cancelAuction()",
	"function refundAll(uint256 maxCount)",
	// Permissionless trustless recovery after EMERGENCY_GRACE if settlement is stuck.
	"function emergencyRefund(uint256 maxCount)",
	"function recoverFromSupplyMismatch(uint256 maxCount)",
	"function recoverFromMintingUnavailable(uint256 maxCount)",
	"function setSchedule(uint64 startTime, uint64 duration)",
	"function setPaused(bool paused)",
	"function rescueSurplusETH(address to)",
	"function rescueERC20(address token, address to, uint256 amount)",
	"function rescueERC721(address token, address to, uint256 tokenId)",
	// events
	"event BidPlaced(uint32 indexed bidId, address indexed bidder, uint96 amount)",
	"event BidIncreased(uint32 indexed bidId, address indexed bidder, uint96 newAmount)",
	"event BidDisplaced(uint32 indexed bidId, address indexed bidder, uint96 amount)",
	"event Refunded(address indexed to, uint256 amount)",
	"event RefundFailed(address indexed to, uint256 amount)",
	"event Extended(uint64 newEndTime, uint32 extensionCount)",
	"event FinalizeStarted(uint96 clearingPrice, uint256 winners)",
	"event Won(uint32 indexed bidId, address indexed winner, uint256 indexed tokenId, uint96 bidAmount, uint96 pricePaid)",
	"event FinalizeProgress(uint256 processed, uint256 total)",
	"event Settled(uint256 proceeds, uint96 clearingPrice, uint256 winners)",
	"event Cancelled()",
	"event EmergencyRefundStarted(uint256 minted, uint256 remaining)",
	"event SupplyMismatchRecoveryStarted(uint256 expectedSupply, uint256 actualSupply, uint256 remaining)",
	"event MintingUnavailableRecoveryStarted(bool operatorAuthorized, uint256 currentMintCap, uint256 requiredMintCap, uint256 minted, uint256 remaining)",
	"event RefundAllProgress(uint256 processed, uint256 total)",
	"event RefundAllComplete()",
	"event ProceedsReleased(uint256 amount, uint256 payoutAShare, uint256 payoutBShare)",
	"event Withdrawn(address indexed to, uint256 amount)",
	"event ScheduleUpdated(uint64 startTime, uint64 endTime, uint64 absoluteEndTime)",
	"event PausedSet(bool paused)",
	"event SurplusETHRescued(address indexed to, uint256 amount)",
	"event ERC20Rescued(address indexed token, address indexed to, uint256 amount)",
	"event ERC721Rescued(address indexed token, address indexed to, uint256 tokenId)",
	// errors (required for decoding custom reverts into readable messages)
	"error InvalidConfig()",
	"error NotActive()",
	"error NotStarted()",
	"error AuctionEnded()",
	"error AuctionNotEnded()",
	"error IsPaused()",
	"error TooManyBids()",
	"error BelowReserve()",
	"error AmountTooLarge()",
	"error BidTooLow(uint256 minRequired)",
	"error NotYourBid()",
	"error ZeroIncrease()",
	"error ZeroBatch()",
	"error NotFinalizable()",
	"error NotOperatorAuthorized()",
	"error InsufficientMintCap()",
	"error NotCancellable()",
	"error NotCancelled()",
	"error NothingToWithdraw()",
	"error NotAuthorizedToFinalize()",
	"error TooLateToConfigure()",
	"error NotYetEmergency()",
	"error AlreadySettled()",
	"error BidIncreaseTooLow(uint256 minRequired)",
	"error UnexpectedSupply(uint256 expected, uint256 actual)",
	"error UnexpectedTokenId(uint256 expected, uint256 actual)",
	"error NoBidFound()",
	"error RecoveryIncomplete()",
	"error NothingToRescue()",
	"error SupplyNotMismatched()",
	"error NotYetMintingUnavailableRecovery()",
	"error MintingStillAvailable()",
]);

// Backwards-compatible aliases: reads and writes both resolve to the unified ABI so every
// call site (and viem's revert decoding) sees the errors and events.
export const panoramaAuctionReadAbi = panoramaAuctionAbi;
export const panoramaAuctionWriteAbi = panoramaAuctionAbi;
